# Generated by Django 4.2.3 on 2023-09-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код набора')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amount_of_usage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_file', models.FileField(upload_to='media', verbose_name='Файл PDF инструкции')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('picture', models.ImageField(upload_to='media', verbose_name='картинка JPG')),
                ('assemblycode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manual.assemblycode', verbose_name='Код-сборки')),
            ],
        ),
    ]
