# Generated by Django 4.2.3 on 2023-09-11 17:20

from django.db import migrations, models
import manual.models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='manual_file',
            field=models.FileField(upload_to=manual.models.Constructor.get_file_name, verbose_name='Файл PDF инструкции'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='picture',
            field=models.ImageField(upload_to=manual.models.Constructor.get_file_name, verbose_name='картинка JPG'),
        ),
    ]
